<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ben_franklin.glb --transform
-->

<script>
	import { T } from '@threlte/core';
	import { Billboard, Text, useGltf } from '@threlte/extras';
	import { DRACOLoader } from 'three/examples/jsm/Addons.js';
	import { DEG2RAD } from 'three/src/math/MathUtils.js';

	let { ref = $bindable(), ...props } = $props();

	const dracoLoader = new DRACOLoader();
	const url = 'http://localhost:5173';
	dracoLoader.setDecoderPath(url + '/draco/');
	const gltf = useGltf(url + '/model/ben.glb', {
		dracoLoader: dracoLoader
	});
</script>

<Billboard position={[-2.5, 2, 0.5]}>
	<Text text="Ben Franklin" fontSize={1} />
	<T.Mesh>
		<T.MeshStandardMaterial color="#FD3F00" toneMapped={false} metalness={1.0} roughness={0.1} />
	</T.Mesh>
</Billboard>

<T.Group bind:ref dispose={false} {...props} scale={3} rotation.x={-DEG2RAD * 0}>
	{#if $gltf}
		<T.Mesh
			receiveShadow
			castShadow
			geometry={$gltf.nodes.Mesh1.geometry}
			material={$gltf.nodes.Mesh1.material}
		/>
	{/if}
</T.Group>
